### ISSUE TITLE
Interruptable tasks tracking issue

### ISSUE THREAD

**Issue by duncanrhamill** [uos3/obc-firmware#35]
# Tracking issue for the interruptable tasks topic

This issue is for tracking of the interruptable tasks topic. The goal of this topic is to determine whether or not OBC tasks should be capable of being interrupted, and if so to design the method in which this will be achieved.

## Necessity

_Are interruptable tasks actually necessary?_

A task would be interrupted if another task of higher priority is waiting to execute. There is one highly time sensitive task for the OBC, the handling of RX data from the comms buffer. This buffer must be serviced before it is full otherwise data could be lost(?). Interruptable tasks would be required if the time taken to fill this buffer is shorter than the duration of any task that could run when data can be recieved.

- [ ] Minimum allowable task duration
  - [ ] Time to fill the buffer
  - [ ] Additional processing time
- [ ] Maximum task duration
  - [ ] Message passing time
  - [ ] OBC processing time

## Design

:warning: _TODO_

## Implementation

:warning: _TODO_
